name: tmx
author: Arron Washington <arron@theradicaledwards.com>
version: 0.9.0
homepage: https://github.com/radicaled/tmx.dart
description: A library for parsing TMX files.
dependencies:
  crypto: ">= 0.8.10+3"
  xml: ">= 0.9.5"
  archive: 1.0.0

dev_dependencies:
  unittest: ">= 0.8.10+3"
