name: tmx
version: 0.11.7
author: Arron Washington <arron@theradicaledwards.com>
description: A library for parsing TMX files.
homepage: https://github.com/radicaled/tmx.dart
dependencies:
  convert: any
  archive: any
  crypto: any
  xml: any
dev_dependencies:
  test: any

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
