name: tmx
version: 0.1.0
authors:
- Fernando Ultremare <feroult@gmail.com>
- Arron Washington (legacy TMX code) <arron@theradicaledwards.com> 
description: A Dart Tiled library.
homepage: https://github.com/feroult/tiled.dart
dependencies:
  convert: ^2.1.1
  archive: ^2.0.5
  crypto: ^2.0.6
  xml: ^3.2.3
dev_dependencies:
  test: any

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
